"""add_notification_preferences_to_patients

Revision ID: 040ab0561e5a
Revises: 9b6f45168c13
Create Date: 2026-04-05 13:22:41.262022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '040ab0561e5a'
down_revision: Union[str, Sequence[str], None] = '9b6f45168c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'notification_preferences')
    # ### end Alembic commands ###
