"""add_pace_preference_eating_habits_image_url

Revision ID: 370efc812ae5
Revises: 861b9d58abdf
Create Date: 2026-03-06 10:11:51.310379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '370efc812ae5'
down_revision: Union[str, Sequence[str], None] = '861b9d58abdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_items', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('patients', sa.Column('pace_preference', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('eating_habits', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'eating_habits')
    op.drop_column('patients', 'pace_preference')
    op.drop_column('food_items', 'image_url')
    # ### end Alembic commands ###
