"""auth_security_columns

Revision ID: 4c38a5d9c2a3
Revises: h8i9j0k1l2m3
Create Date: 2026-03-20 09:59:58.933466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c38a5d9c2a3'
down_revision: Union[str, Sequence[str], None] = 'h8i9j0k1l2m3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('admins', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('doctors', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('doctors', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('doctors', 'is_accepting',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('patients', sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('patients', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('patients', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'token_1_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'renewal_requested',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'expiring_soon',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'expiring_soon',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'renewal_requested',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'token_1_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('patients', 'is_email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('patients', 'password_changed_at')
    op.drop_column('patients', 'locked_until')
    op.drop_column('patients', 'failed_login_attempts')
    op.alter_column('doctors', 'is_accepting',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('doctors', 'locked_until')
    op.drop_column('doctors', 'failed_login_attempts')
    op.drop_column('admins', 'locked_until')
    op.drop_column('admins', 'failed_login_attempts')
    # ### end Alembic commands ###
