"""add_all_user_tables

Revision ID: 4e5124b3e103
Revises: 92084b0bc541
Create Date: 2026-03-05 12:18:14.227031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e5124b3e103'
down_revision: Union[str, Sequence[str], None] = '92084b0bc541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('allowed_ips', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('clinic_name', sa.String(), nullable=True),
    sa.Column('clinic_address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('mfa_secret', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Numeric(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=False),
    sa.Column('activity_level', sa.String(length=5), nullable=False),
    sa.Column('diet_type', sa.String(length=30), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('health_condition', sa.String(length=30), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bmr', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('tdee', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('target_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('health_goals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('medical_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('food_allergies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dietary_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('fasting_days', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sleep_hours', sa.Numeric(), nullable=True),
    sa.Column('water_glasses', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('smoking', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disclaimer_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nonveg_meals_per_week', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('water_glasses', sa.Integer(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('calories_burned', sa.Numeric(), nullable=True),
    sa.Column('total_calories_consumed', sa.Numeric(), nullable=True),
    sa.Column('protein_pct', sa.Numeric(), nullable=True),
    sa.Column('carbs_pct', sa.Numeric(), nullable=True),
    sa.Column('fat_pct', sa.Numeric(), nullable=True),
    sa.Column('streak_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'log_date', name='uq_progress_patient_date')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingredient_checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('generated_by', sa.String(length=20), nullable=True),
    sa.Column('doctor_notes', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_patient', 'recommendations', ['patient_id'], unique=False)
    op.create_table('subscription_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('used_by_patient_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['used_by_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('custom_food_name', sa.String(), nullable=True),
    sa.Column('calories_consumed', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('portion_servings', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ml_patient_date', 'meal_logs', ['patient_id', 'logged_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ml_patient_date', table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_table('subscription_codes')
    op.drop_index('idx_rec_patient', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('progress_logs')
    op.drop_table('patient_requests')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_table('admins')
    # ### end Alembic commands ###
