"""add_calorie_adjustment_to_progress_logs

Revision ID: 861b9d58abdf
Revises: cf7a21f007f0
Create Date: 2026-03-05 21:19:08.306650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861b9d58abdf'
down_revision: Union[str, Sequence[str], None] = 'cf7a21f007f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress_logs', sa.Column('calorie_adjustment', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress_logs', 'calorie_adjustment')
    # ### end Alembic commands ###
