"""food_items_and_templates

Revision ID: 92084b0bc541
Revises: 
Create Date: 2026-02-27 21:15:45.947147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92084b0bc541'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_name', sa.String(length=255), nullable=False),
    sa.Column('slot_type', sa.String(length=50), nullable=False),
    sa.Column('cal_per_serving', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('protein_per_serving', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('carbs_per_serving', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fat_per_serving', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('fiber_per_serving', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sodium_per_serving', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('serving_weight_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('diet_type', sa.String(length=30), nullable=False),
    sa.Column('region_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('meal_time_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('plan_type_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('ingredients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fi_diet', 'food_items', ['diet_type'], unique=False)
    op.create_index('idx_fi_slot', 'food_items', ['slot_type'], unique=False)
    op.create_index('idx_fi_verified', 'food_items', ['is_verified'], unique=False)
    op.execute("CREATE INDEX idx_fi_regions ON food_items USING GIN (region_tags);")
    op.execute("CREATE INDEX idx_fi_meal_times ON food_items USING GIN (meal_time_tags);")
    op.execute("CREATE INDEX idx_fi_plan_types ON food_items USING GIN (plan_type_tags);")
    op.create_table('meal_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_time', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=10), nullable=False),
    sa.Column('diet_type', sa.String(length=30), nullable=False),
    sa.Column('plan_type', sa.String(length=30), nullable=False),
    sa.Column('slots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_time', 'region', 'diet_type', 'plan_type', name='uq_template')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX idx_fi_plan_types;")
    op.execute("DROP INDEX idx_fi_meal_times;")
    op.execute("DROP INDEX idx_fi_regions;")
    op.drop_table('meal_templates')
    op.drop_index('idx_fi_verified', table_name='food_items')
    op.drop_index('idx_fi_slot', table_name='food_items')
    op.drop_index('idx_fi_diet', table_name='food_items')
    op.drop_table('food_items')
    # ### end Alembic commands ###
