"""add_fcm_token_to_patients

Revision ID: 9b6f45168c13
Revises: 4c38a5d9c2a3
Create Date: 2026-03-20 19:23:24.929039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6f45168c13'
down_revision: Union[str, Sequence[str], None] = '4c38a5d9c2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('fcm_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'fcm_token')
    # ### end Alembic commands ###
